In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname="C:/Windows/Fonts/HANYGO230.ttf").get_name()
plt.rc("font",family=font_name)

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"] = False

import seaborn as sns

#import warnings
#warnings.filterwarnings("ignore")

In [5]:
import mglearn
from sklearn.datasets import load_breast_cancer, load_boston, load_iris, make_moons
from sklearn.datasets import load_digits, load_wine, load_diabetes, make_blobs

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, cross_validate, KFold
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler,MinMaxScaler

from sklearn.feature_extraction.text import CountVectorizer 
#단어의 수를 세주는 자연어처리에 사용하는 객체

In [6]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier

import xgboost as xgb
# 방법 1. conda install -c anaconda py-xgboost 로 설치후 xgb 사용(성능 더좋음)
# 방법 2. from xgbost import XGBClassifier. XGBRegressor 사용(사용법 비슷해서 편리)
from xgboost import XGBClassifier, XGBRegressor
from xgboost import plot_importance, plot_tree

from lightgbm import LGBMClassifier, LGBMRegressor
from lightgbm import plot_importance, plot_metric, plot_tree

from sklearn.svm import SVR, SVC

from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

from sklearn.cluster import KMeans

from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier

import statsmodels.api as sm

from sklearn.tree import export_graphviz
import graphviz

In [7]:
pd.set_option('display.max_rows',1000)

## df 최신버전 가져오기(현재 버전:ver3)

In [12]:
import os
os.getcwd()

'C:\\workspace\\git\\git_projects\\Movie_project\\Preprocessing'

In [13]:
df = pd.read_csv("../Data/train/data_ver3.csv", index_col=0,thousands = ',')

# 원본 기본 전처리 및 저장

In [6]:
df1 = pd.read_csv("Data/train/KOBIS_기간별박스오피스_2011-2012.csv", header=5)
df2 = pd.read_csv("Data/train/KOBIS_기간별박스오피스_2013-2014.csv", header=5)
df3 = pd.read_csv("Data/train/KOBIS_기간별박스오피스_2015-2016.csv", header=5)
df4 = pd.read_csv("Data/train/KOBIS_기간별박스오피스_2017-2018.csv", header=5)
df5 = pd.read_csv("Data/train/KOBIS_기간별박스오피스_2019-2020.csv", header=5)

In [7]:
#열이름 변경
cols=["순위","영화명","개봉일","매출액","점유율","누적매출액","관객수","누적관객수",
      "스크린수","상영횟수","대표국적","국적","제작사","배급사",
      "등급","장르","감독","배우"]

df=pd.concat([df1,df2,df3,df4,df5])
df.columns=cols

In [9]:
#원본 저장
df.to_csv("data.csv",encoding = 'utf-8-sig')

In [10]:
### 합계표시 된 행 제거
df.drop(df.loc[df.loc[:]["순위"]=="합계"].index, inplace=True)

In [16]:
#순위, 국적 제거
df.drop(["순위"],axis=1, inplace=True)
df.drop(["국적"],axis=1, inplace=True)

In [17]:
#점유율, 제작사 제거
df.drop(["점유율"],axis=1, inplace=True)
df.drop(["제작사"],axis=1, inplace=True)

In [18]:
#인덱스 초기화
df.reset_index(inplace=True)
df.drop(["index"],axis=1, inplace=True)

In [28]:
#인덱스 이상하게 설정됐을 경우
df.drop(["level_0"],axis=1, inplace=True)

KeyError: "['level_0'] not found in axis"

In [21]:
df.head()

,영화명,개봉일,매출액,누적매출액,관객수,누적관객수,스크린수,상영횟수,대표국적,배급사,등급,장르,감독,배우
0,도둑들,2012-07-25,"93,664,808,500","93,664,808,500","12,983,178","12,983,178","1,091","155,392",한국,(주)쇼박스,15세이상관람가,"액션,범죄",최동훈,"김윤석,김혜수,이정재,전지현,임달화,김해숙,오달수,김수현,이심결,증국상,서영주,장동..."
1,"광해, 왕이 된 남자",2012-09-13,"88,899,448,769","88,899,448,769","12,319,390","12,319,390","1,001","203,400",한국,(주)씨제이이엔엠,15세이상관람가,"사극,드라마",추창민,"이병헌,류승룡,한효주,장광,김인권,심은경,김명곤,서진원,장재현,정창국,조혜정,김남준..."
2,트랜스포머 3,2011-06-29,"74,840,681,500","74,840,681,500","7,784,743","7,784,743","1,409","124,450",미국,(주)씨제이이엔엠,12세이상관람가,"액션,어드벤처",마이클 베이,"조쉬 더하멜,존 말코비치,로지 헌팅턴-휘틀리,샤이아 라보프,패트릭 뎀시"
3,미션임파서블:고스트프로토콜,2011-12-15,"57,301,924,000","57,301,924,000","7,508,896","7,508,896","1,024","114,765",미국,(주)씨제이이엔엠,15세이상관람가,액션,브래드 버드,"톰 크루즈,제레미 레너"
4,최종병기 활,2011-08-10,"55,827,861,500","55,827,861,500","7,470,633","7,470,633",615,"130,054",한국,롯데쇼핑㈜롯데엔터테인먼트,15세이상관람가,"사극,액션",김한민,"박해일,류승룡,김무열,문채원,이한위,김구택,이경영,박기웅,이승준,이재구,박노식,이다..."

#### df 합본 저장

In [22]:
df.to_csv("data_ver1.csv",encoding = 'utf-8-sig')

#### (2) 등급 세분화

In [49]:
df["등급"].value_counts()

청소년관람불가                             8743
15세이상관람가                            4915
전체관람가                               3102
12세이상관람가                            2973
고등학생이상관람가                            315
연소자관람불가                              314
12세관람가                               253
15세관람가                               246
18세관람가                               207
중학생이상관람가                             165
연소자관람가                               154
국민학생관람불가                             112
고등학생이상관람가,15세이상관람가                    54
연소자관람불가,청소년관람불가                       49
18세 미만인 자는 관람할 수 없는 등급                49
미정                                    43
15세 미만인 자는 관람할 수 없는 등급                36
미성년자관람불가                              34
15세관람가,15세이상관람가                       33
18세관람가,청소년관람불가                        31
12세이상관람가,12세관람가                       26
12세 미만인 자는 관람할 수 없는 등급                24
연소자관람가,전체관람가                          23
15세이상관람가,중학생이상관람가                     21
청소년관람불가,15세이상관람가                      20
모든 관람객이 관람할 수 있는 등급                   16
12세이상관람가,전체관람가                        11
연소자관람불가,15세이상관람가                      11
12세이상관람가,중학생이상관람가                     11
12세이상관람가,15세이상관람가                      6
청소년관람불가,고등학생이상관람가                      5
15세 미만인 자는 관람할 수 없는 등급 ,15세이상관람가       5
12세이상관람가,연소자관람가                        5
12세이상관람가,국민학생관람불가,15세이상관람가             5
12세이상관람가,국민학생관람불가                      5
12세이상관람가,연소자관람가,전체관람가                  5
청소년관람불가,전체관람가                          5
미성년자관람가                                5
15세이상관람가,전체관람가                         4
국민학생관람불가,청소년관람불가                       4
기타                                     4
15세이상관람가,18세 미만인 자는 관람할 수 없는 등급        4
국민학생관람불가,15세이상관람가                      4
12세이상관람가,15세 미만인 자는 관람할 수 없는 등급        3
청소년관람불가,12세관람가                         3
모든 관람객이 관람할 수 있는 등급,전체관람가              2
18세관람가,15세이상관람가                        2
연소자관람가,15세이상관람가                        2
고등학생이상관람가,청소년관람불가                      2
12세이상관람가,고등학생이상관람가                     2
15세이상관람가,미성년자관람불가                      1
15세관람가,12세이상관람가                        1
Name: 등급, dtype: int64

In [41]:
no_18 = ["18세관람가","연소자관람불가","연소자관람불가,청소년관람불가",
          "18세 미만인 자는 관람할 수 없는 등급",
          "미성년자관람불가","18세관람가,청소년관람불가"
          "청소년관람불가,고등학생이상관람가","국민학생관람불가,청소년관람불가",
          "청소년관람불가,12세관람가","고등학생이상관람가,청소년관람불가"]

In [42]:
df[df["등급"].isin(no_18)]["등급"].value_counts()

연소자관람불가                   314
18세관람가                    207
연소자관람불가,청소년관람불가            49
18세 미만인 자는 관람할 수 없는 등급     49
미성년자관람불가                   34
국민학생관람불가,청소년관람불가            4
청소년관람불가,12세관람가              3
고등학생이상관람가,청소년관람불가           2
Name: 등급, dtype: int64

In [43]:
df[df["등급"]=="18세관람가,청소년관람불가"]

,Unnamed: 0,영화명,개봉일,매출액,점유율,누적매출액,관객수,누적관객수,스크린수,상영횟수,대표국적,제작사,배급사,등급,장르,감독,배우
1310,1310,매치 포인트,2006-04-13,"1,963,500",0.00%,"847,620,600",272,"128,056",1,13,영국,비비씨필름즈,"(주)퍼스트런,글뫼 주식회사,CJ ENM","18세관람가,청소년관람불가",멜로/로맨스,우디 알렌,"조나단 리스 마이어스,스칼렛 요한슨"
1328,1328,피아니스트,2002-12-20,"2,070,000",0.00%,"2,604,900",265,336,1,12,프랑스,NaN,"(주)블룸즈베리리소시스리미티드,(주)엠앤드엔엔터테인먼트","18세관람가,청소년관람불가",드라마,미카엘 하네케,"이자벨 위페르,브누와 마지멜"
1372,1372,클로저,2005-02-03,"711,000",0.00%,"1,450,069,000",237,"220,542",2,7,미국,워너 브러더스 텔레비전,"(주)스튜디오디에이치엘,(주)퍼스트런,글뫼 주식회사,소니픽쳐스릴리징코리아","18세관람가,청소년관람불가",멜로/로맨스,마이크 니콜스,"나탈리 포트만,주드 로,줄리아 로버츠,클라이브 오웬"
2421,2421,벨벳 골드마인,1999-08-28,"504,000",0.00%,"504,000",73,73,1,1,영국,"채널4필름,골드윈필름,킬러 필름즈,미라맥스 필름즈,뉴마켓 캐피탈 그룹","(주)디스테이션,(주)엔케이컨텐츠","18세관람가,청소년관람불가",드라마,토드 헤인즈,"이완 맥그리거,조나단 리스 마이어스,크리스찬 베일,토니 콜레뜨"
5806,5806,벨벳 골드마인,1999-08-28,"39,877,908",0.00%,"40,381,908","5,003","5,076",8,217,영국,"채널4필름,골드윈필름,킬러 필름즈,미라맥스 필름즈,뉴마켓 캐피탈 그룹","(주)디스테이션,(주)엔케이컨텐츠","18세관람가,청소년관람불가",드라마,토드 헤인즈,"이완 맥그리거,조나단 리스 마이어스,크리스찬 베일,토니 콜레뜨"
6710,6710,파이트 클럽,1999-11-13,"3,369,000",0.00%,"3,369,000",547,547,1,8,미국,"아트린슨프로덕션즈,폭스2000픽처스,리젠시 엔터프라이즈,타우러스 필름",(주)팝엔터테인먼트,"18세관람가,청소년관람불가",액션,데이빗 핀처,"브래드 피트,에드워드 노튼,헬레나 본햄 카터"
6943,6943,매치 포인트,2006-04-13,"2,220,000",0.00%,"849,840,600",358,"128,414",1,8,영국,비비씨필름즈,"(주)퍼스트런,글뫼 주식회사,CJ ENM","18세관람가,청소년관람불가",멜로/로맨스,우디 알렌,"조나단 리스 마이어스,스칼렛 요한슨"
7034,7034,박하사탕,2000-01-01,"2,366,500",0.00%,"2,872,500",302,378,1,8,한국,"(주)이스트필름,파인하우스필름(주)","CGV아트하우스,(주)신도필림","18세관람가,청소년관람불가",드라마,이창동,"설경구,문소리,김여진,이병철,공형진,이대연,최덕문,박길수,지대한,유승목,손영순,박성..."
7208,7208,피아니스트,2002-12-20,"1,835,500",0.00%,"4,440,400",235,571,1,7,프랑스,NaN,"(주)블룸즈베리리소시스리미티드,(주)엠앤드엔엔터테인먼트","18세관람가,청소년관람불가",드라마,미카엘 하네케,"이자벨 위페르,브누와 마지멜"
7544,7544,2046,2004-10-15,"1,264,000",0.00%,"797,104,500",149,"123,062",1,6,홍콩,"아르떼,콜럼비아 픽쳐스 코포레이션,프랑스3시네마,젯톤프로덕션,제2 독일 텔레비젼 협...","(주)디스테이션,이십세기폭스필름코퍼레이션","18세관람가,청소년관람불가",드라마,왕가위,"양조위,공리,왕비,기무라 다쿠야,장쯔이,유가령,장첸,장만옥"
7967,7967,죽거나 혹은 나쁘거나,2000-07-15,"565,300",0.00%,"565,300",93,93,1,3,한국,"(주)외유내강,씨앤피엔터테인먼트(주)",(주)라이크콘텐츠,"18세관람가,청소년관람불가",드라마,류승완,"류승완,류승범,박성빈,배중식,김수현,정재영,임원희,안길강,기주봉,천성훈,박성일"
11846,11846,파이트 클럽,1999-11-13,"121,231,200",0.00%,"124,600,200","15,224","15,771",70,"1,217",미국,"아트린슨프로덕션즈,폭스2000픽처스,리젠시 엔터프라이즈,타우러스 필름",(주)팝엔터테인먼트,"18세관람가,청소년관람불가",액션,데이빗 핀처,"브래드 피트,에드워드 노튼,헬레나 본햄 카터"
12039,12039,그녀에게,2003-04-18,"46,103,252",0.00%,"52,429,252","6,003","7,032",19,355,스페인,NaN,"판씨네마(주),(주)미로비젼","18세관람가,청소년관람불가",멜로/로맨스,페드로 알모도바르,"하비에 카마라,다리오 그랜디네티,레오노르 와틀링,로자리오 플로레스"
12060,12060,피아니스트,2002-12-20,"29,720,050",0.00%,"34,160,450","5,458","6,029",22,344,프랑스,NaN,"(주)블룸즈베리리소시스리미티드,(주)엠앤드엔엔터테인먼트","18세관람가,청소년관람불가",드라마,미카엘 하네케,"이자벨 위페르,브누와 마지멜"
13166,13166,벨벳 골드마인,1999-08-28,"3,457,500",0.00%,"43,839,408",426,"5,502",1,13,영국,"채널4필름,골드윈필름,킬러 필름즈,미라맥스 필름즈,뉴마켓 캐피탈 그룹","(주)디스테이션,(주)엔케이컨텐츠","18세관람가,청소년관람불가",드라마,토드 헤인즈,"이완 맥그리거,조나단 리스 마이어스,크리스찬 베일,토니 콜레뜨"
14488,14488,박하사탕,2000-01-01,"750,000",0.00%,"3,622,500",92,470,1,3,한국,"(주)이스트필름,파인하우스필름(주)","CGV아트하우스,(주)신도필림","18세관람가,청소년관람불가",드라마,이창동,"설경구,문소리,김여진,이병철,공형진,이대연,최덕문,박길수,지대한,유승목,손영순,박성..."
15770,15770,죽거나 혹은 나쁘거나,2000-07-15,"162,000",0.00%,"727,300",30,123,1,6,한국,"(주)외유내강,씨앤피엔터테인먼트(주)",(주)라이크콘텐츠,"18세관람가,청소년관람불가",드라마,류승완,"류승완,류승범,박성빈,배중식,김수현,정재영,임원희,안길강,기주봉,천성훈,박성일"
18657,18657,클로저,2005-02-03,"179,775,032",0.00%,"1,629,844,032","24,159","244,701",99,"2,342",미국,워너 브러더스 텔레비전,"(주)스튜디오디에이치엘,(주)퍼스트런,글뫼 주식회사,소니픽쳐스릴리징코리아","18세관람가,청소년관람불가",멜로/로맨스,마이크 니콜스,"나탈리 포트만,주드 로,줄리아 로버츠,클라이브 오웬"
18871,18871,박하사탕,2000-01-01,"80,368,600",0.00%,"83,991,100","8,971","9,441",35,783,한국,"(주)이스트필름,파인하우스필름(주)","CGV아트하우스,(주)신도필림","18세관람가,청소년관람불가",드라마,이창동,"설경구,문소리,김여진,이병철,공형진,이대연,최덕문,박길수,지대한,유승목,손영순,박성..."
19042,19042,매치 포인트,2006-04-13,"30,143,448",0.00%,"879,984,048","4,192","132,606",43,538,영국,비비씨필름즈,"(주)퍼스트런,글뫼 주식회사,CJ ENM","18세관람가,청소년관람불가",멜로/로맨스,우디 알렌,"조나단 리스 마이어스,스칼렛 요한슨"
20181,20181,벨벳 골드마인,1999-08-28,"2,854,577",0.00%,"46,693,985",431,"5,933",1,10,영국,"채널4필름,골드윈필름,킬러 필름즈,미라맥스 필름즈,뉴마켓 캐피탈 그룹","(주)디스테이션,(주)엔케이컨텐츠","18세관람가,청소년관람불가",드라마,토드 헤인즈,"이완 맥그리거,조나단 리스 마이어스,크리스찬 베일,토니 콜레뜨"
20452,20452,파이트 클럽,1999-11-13,"1,899,000",0.00%,"126,499,200",282,"16,053",1,6,미국,"아트린슨프로덕션즈,폭스2000픽처스,리젠시 엔터프라이즈,타우러스 필름",(주)팝엔터테인먼트,"18세관람가,청소년관람불가",액션,데이빗 핀처,"브래드 피트,에드워드 노튼,헬레나 본햄 카터"
20713,20713,피아니스트,2002-12-20,"1,342,000",0.00%,"35,502,450",217,"6,246",1,5,프랑스,NaN,"(주)블룸즈베리리소시스리미티드,(주)엠앤드엔엔터테인먼트","18세관람가,청소년관람불가",드라마,미카엘 하네케,"이자벨 위페르,브누와 마지멜"
22322,22322,그녀에게,2003-04-18,"407,000",0.00%,"52,836,252",67,"7,099",1,3,스페인,NaN,"판씨네마(주),(주)미로비젼","18세관람가,청소년관람불가",멜로/로맨스,페드로 알모도바르,"하비에 카마라,다리오 그랜디네티,레오노르 와틀링,로자리오 플로레스"
27994,27994,죽거나 혹은 나쁘거나,2000-07-15,"11,797,700",0.00%,"12,525,000","1,349","1,472",21,217,한국,"(주)외유내강,씨앤피엔터테인먼트(주)",(주)라이크콘텐츠,"18세관람가,청소년관람불가",드라마,류승완,"류승완,류승범,박성빈,배중식,김수현,정재영,임원희,안길강,기주봉,천성훈,박성일"
28051,28051,벨벳 골드마인,1999-08-28,"7,108,500",0.00%,"53,802,485","1,224","7,157",27,243,영국,"채널4필름,골드윈필름,킬러 필름즈,미라맥스 필름즈,뉴마켓 캐피탈 그룹","(주)디스테이션,(주)엔케이컨텐츠","18세관람가,청소년관람불가",드라마,토드 헤인즈,"이완 맥그리거,조나단 리스 마이어스,크리스찬 베일,토니 콜레뜨"
28390,28390,파이트 클럽,1999-11-13,"4,444,000",0.00%,"130,943,200",696,"16,749",2,51,미국,"아트린슨프로덕션즈,폭스2000픽처스,리젠시 엔터프라이즈,타우러스 필름",(주)팝엔터테인먼트,"18세관람가,청소년관람불가",액션,데이빗 핀처,"브래드 피트,에드워드 노튼,헬레나 본햄 카터"
28639,28639,박하사탕,2000-01-01,"4,013,900",0.00%,"88,005,000",456,"9,897",6,43,한국,"(주)이스트필름,파인하우스필름(주)","CGV아트하우스,(주)신도필림","18세관람가,청소년관람불가",드라마,이창동,"설경구,문소리,김여진,이병철,공형진,이대연,최덕문,박길수,지대한,유승목,손영순,박성..."
29173,29173,매치 포인트,2006-04-13,"1,803,000",0.00%,"881,787,048",228,"132,834",1,10,영국,비비씨필름즈,"(주)퍼스트런,글뫼 주식회사,CJ ENM","18세관람가,청소년관람불가",멜로/로맨스,우디 알렌,"조나단 리스 마이어스,스칼렛 요한슨"
29514,29514,피아니스트,2002-12-20,"932,000",0.00%,"36,434,450",165,"6,411",1,2,프랑스,NaN,"(주)블룸즈베리리소시스리미티드,(주)엠앤드엔엔터테인먼트","18세관람가,청소년관람불가",드라마,미카엘 하네케,"이자벨 위페르,브누와 마지멜"
30830,30830,그녀에게,2003-04-18,"534,000",0.00%,"53,370,252",51,"7,150",1,8,스페인,NaN,"판씨네마(주),(주)미로비젼","18세관람가,청소년관람불가",멜로/로맨스,페드로 알모도바르,"하비에 카마라,다리오 그랜디네티,레오노르 와틀링,로자리오 플로레스"

In [ ]:
"18세관람가,청소년관람불가"
          "청소년관람불가,고등학생이상관람가"

### 중복 제거

In [17]:
(df["영화명"].value_counts() >1).value_counts()

False    22302
True      4805
Name: 영화명, dtype: int64

#### (3) 장르 통일

In [27]:
## nan값 확인 후 처리
df["장르"].isnull().sum() #결측값 1421개

1421

In [28]:
for i in range(len(df["장르"])):
    if type(df["장르"][i]) == float:
        df["장르"][i] = "장르없음"
    else:
        df["장르"][i] = df["장르"][i].split(",")[0]

In [29]:
df["장르"].value_counts()

드라마         9244
멜로/로맨스      4340
다큐멘터리       3272
기타          3206
애니메이션       3003
액션          2227
코미디         1842
성인물(에로)     1766
장르없음        1421
공포(호러)       893
스릴러          687
범죄           685
SF           370
공연           316
미스터리         290
어드벤처         279
전쟁           253
서부극(웨스턴)     224
판타지          215
사극           213
가족           198
뮤지컬          138
Name: 장르, dtype: int64

In [31]:
#기타장르 제거
guitar_idx = df[df["장르"]=="기타"].index
df.drop(guitar_idx, inplace=True)

#### 파일 내보내기(ver2)

In [32]:
df.to_csv("data_ver2.csv",encoding = 'utf-8-sig')

### 데이터 타입 변경

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31876 entries, 0 to 35081
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   영화명     31875 non-null  object
 1   개봉일     19839 non-null  object
 2   매출액     31876 non-null  object
 3   누적매출액   31876 non-null  object
 4   관객수     31876 non-null  object
 5   누적관객수   31876 non-null  object
 6   스크린수    31876 non-null  object
 7   상영횟수    31876 non-null  object
 8   대표국적    31317 non-null  object
 9   배급사     18501 non-null  object
 10  등급      21823 non-null  object
 11  장르      31876 non-null  object
 12  감독      27646 non-null  object
 13  배우      19871 non-null  object
dtypes: object(14)
memory usage: 3.6+ MB

In [82]:
df = df.astype({'매출액': 'int','누적매출액': 'int','관객수': 'int',
                '누적관객수': 'int','스크린수': 'int','상영횟수': 'int'})

### 중복값 제거

In [92]:
df_sorted = df.sort_values(["감독","누적관객수","누적매출액"], ascending=True)

In [93]:
df_sorted[df_sorted["영화명"]=="로미오와 줄리엣"]

,영화명,개봉일,매출액,누적매출액,관객수,누적관객수,스크린수,상영횟수,대표국적,배급사,등급,장르,감독,배우
7807,로미오와 줄리엣,2014-10-23,1505000,1505000,110,110,7,45,미국,(주) 인스터 글로벌,전체관람가,공연,데이빗 리보스,올랜도 블룸
14030,로미오와 줄리엣,2014-10-23,1761000,3266000,142,252,1,7,미국,(주) 인스터 글로벌,전체관람가,공연,데이빗 리보스,올랜도 블룸
6743,로미오와 줄리엣,NaN,1010000,1010000,505,505,1,12,영국,NaN,NaN,멜로/로맨스,레나토 카스텔라니,로렌스 하비
12388,로미오와 줄리엣,NaN,4101000,5111000,2038,2543,1,16,영국,NaN,NaN,멜로/로맨스,레나토 카스텔라니,로렌스 하비
20548,로미오와 줄리엣,NaN,498000,5609000,249,2792,1,15,영국,NaN,NaN,멜로/로맨스,레나토 카스텔라니,로렌스 하비
30791,로미오와 줄리엣,NaN,106000,5715000,53,2845,1,6,영국,NaN,NaN,멜로/로맨스,레나토 카스텔라니,로렌스 하비
5557,로미오와 줄리엣,1996-12-28,84831500,84831500,12679,12679,47,1208,미국,"이십세기폭스코리아(주),(주)프레인글로벌",고등학생이상관람가,멜로/로맨스,바즈 루어만,"레오나르도 디카프리오,클레어 데인즈"
13000,로미오와 줄리엣,1996-12-28,4212400,89043900,569,13248,4,37,미국,"이십세기폭스코리아(주),(주)프레인글로벌",고등학생이상관람가,멜로/로맨스,바즈 루어만,"레오나르도 디카프리오,클레어 데인즈"
22422,로미오와 줄리엣,1996-12-28,372500,89416400,62,13310,1,4,미국,"이십세기폭스코리아(주),(주)프레인글로벌",고등학생이상관람가,멜로/로맨스,바즈 루어만,"레오나르도 디카프리오,클레어 데인즈"
27426,로미오와 줄리엣,1996-12-28,55037000,144453400,6982,20292,57,554,미국,"이십세기폭스코리아(주),(주)프레인글로벌",고등학생이상관람가,멜로/로맨스,바즈 루어만,"레오나르도 디카프리오,클레어 데인즈"
19720,로미오와 줄리엣,2018-05-20,22906500,22906500,988,988,11,99,독일,(주)케빈앤컴퍼니,12세이상관람가,공연,위르겐 플림,"후안 디에고 플로레즈,아이다 가리풀리나"
34930,로미오와 줄리엣,NaN,0,0,0,0,7,51,영국,NaN,NaN,공연,케네스 맥밀란,NaN
6574,로미오와 줄리엣,2013-09-26,10927500,10927500,776,776,12,86,영국,(주) 인스터 글로벌,전체관람가,공연,케네스 맥밀란,NaN
2439,로미오와 줄리엣,1978-12-30,346000,346000,71,71,1,3,영국,NaN,12세관람가,드라마,프랑코 제피렐리,"레오나르드 화이팅,올리비아 핫세,밀로 오세아"
14288,로미오와 줄리엣,1978-12-30,892000,1238000,111,182,2,10,영국,NaN,12세관람가,드라마,프랑코 제피렐리,"레오나르드 화이팅,올리비아 핫세,밀로 오세아"
21230,로미오와 줄리엣,1978-12-30,284000,1522000,142,324,1,3,영국,NaN,12세관람가,드라마,프랑코 제피렐리,"레오나르드 화이팅,올리비아 핫세,밀로 오세아"
19544,로미오와 줄리엣,2017-06-03,30322500,30322500,1306,1306,11,72,미국,(주) 인스터 글로벌,전체관람가,공연,NaN,NaN

In [94]:
df_sorted = df_sorted.drop_duplicates(['영화명',"감독"], keep = 'last')

In [95]:
df_sorted[df_sorted["영화명"]=="로미오와 줄리엣"]

,영화명,개봉일,매출액,누적매출액,관객수,누적관객수,스크린수,상영횟수,대표국적,배급사,등급,장르,감독,배우
14030,로미오와 줄리엣,2014-10-23,1761000,3266000,142,252,1,7,미국,(주) 인스터 글로벌,전체관람가,공연,데이빗 리보스,올랜도 블룸
30791,로미오와 줄리엣,NaN,106000,5715000,53,2845,1,6,영국,NaN,NaN,멜로/로맨스,레나토 카스텔라니,로렌스 하비
27426,로미오와 줄리엣,1996-12-28,55037000,144453400,6982,20292,57,554,미국,"이십세기폭스코리아(주),(주)프레인글로벌",고등학생이상관람가,멜로/로맨스,바즈 루어만,"레오나르도 디카프리오,클레어 데인즈"
19720,로미오와 줄리엣,2018-05-20,22906500,22906500,988,988,11,99,독일,(주)케빈앤컴퍼니,12세이상관람가,공연,위르겐 플림,"후안 디에고 플로레즈,아이다 가리풀리나"
6574,로미오와 줄리엣,2013-09-26,10927500,10927500,776,776,12,86,영국,(주) 인스터 글로벌,전체관람가,공연,케네스 맥밀란,NaN
21230,로미오와 줄리엣,1978-12-30,284000,1522000,142,324,1,3,영국,NaN,12세관람가,드라마,프랑코 제피렐리,"레오나르드 화이팅,올리비아 핫세,밀로 오세아"
19544,로미오와 줄리엣,2017-06-03,30322500,30322500,1306,1306,11,72,미국,(주) 인스터 글로벌,전체관람가,공연,NaN,NaN

In [98]:
df_sorted.shape

(24883, 14)

#### 파일 내보내기(ver3) : 중복값 제거

In [36]:
df_sorted.to_csv("data_ver3.csv",encoding = 'utf-8-sig')

NameError: name 'df_sorted' is not defined

### 누적 매출액, 누적 관객수 0 인 행 삭제

In [31]:
zero_index1= df[df["누적관객수"]==0].index

In [32]:
df.drop(zero_index1, inplace=True)

In [29]:
zero_index2= df[df["누적매출액"]==0].index

In [33]:
df.drop(zero_index2, inplace=True)

#### 파일 내보내기(ver4) : 중복값 제거

In [39]:
df.to_csv("../Data/train/data_ver4.csv",encoding = 'utf-8-sig')

### 크롤링을 통한 결측값 업데이트

In [ ]:

# 링크 접속
def url_search(movie_name):
    url1 = "https://movie.naver.com/movie/search/result.naver?query={}&section=all&ie=utf8".format(movie_name)
    html1 = requests.get(url1)
    soup1 = BeautifulSoup(html1.text, 'html.parser')
    
    return soup1

In [ ]:

# href 태그 찾기

def href_tag(soup1):

    tag_search_list1 = soup1.find("ul", class_ = "search_list_1")
    
    if bool(tag_search_list1) == True:
        tag_a = soup1.select('div#old_content > ul.search_list_1 > li > p.result_thumb > a')
        global href
        for i in tag_a:
            href = i.attrs['href']
    
        return href
    
    else:
        return "없음"

In [ ]:
# 해당 페이지 링크 가져오기

def find_link(href):
    
    if href != "없음":
        url2 = "https://movie.naver.com{}".format(href)
        html2 = requests.get(url2)
        soup2 = BeautifulSoup(html2.text, 'html.parser')
    
        return soup2
    
    else:
        return "없음"

In [ ]:
# dd 태그 찾기

def dd_tag(soup2):
    
    if soup2 != "없음":
        find_dir = soup2.find_all('dd')
    
        return find_dir
    
    else:
        return "없음"

In [ ]:
# director 찾기
def find_director(find_dir):
    
    if find_dir != "없음":
        words = []
    
        for i in find_dir:
            i = i.get_text()
            tmp = []
            tmp.append(i)
        
            for w in tmp:
                w = w.strip('\n')
                words.append(w)
                director = words[0].split(',')[0]
        
            return director
    
    else:
        return "없음"

In [ ]:
# 네이버 영화 감독 정보 크롤링

# 링크 접속
def url_search(movie_name):
    url1 = "https://movie.naver.com/movie/search/result.naver?query={}&section=all&ie=utf8".format(movie_name)
    html1 = requests.get(url1)
    soup1 = BeautifulSoup(html1.text, 'html.parser')
    
    return soup1

# href 태그 찾기

def href_tag(soup1):

    tag_search_list1 = soup1.find("ul", class_ = "search_list_1")
    
    if bool(tag_search_list1) == True:
        tag_a = soup1.select('div#old_content > ul.search_list_1 > li > p.result_thumb > a')
        global href
        for i in tag_a:
            href = i.attrs['href']
    
        return href
    
    else:
        return "없음"
    

# 해당 페이지 링크 가져오기

def find_link(href):
    
    if href != "없음":
        url2 = "https://movie.naver.com{}".format(href)
        html2 = requests.get(url2)
        soup2 = BeautifulSoup(html2.text, 'html.parser')
    
        return soup2
    
    else:
        return "없음"

# dd 태그 찾기

def dd_tag(soup2):
    
    if soup2 != "없음":
        find_dir = soup2.find_all('dd')
    
        return find_dir
    
    else:
        return "없음"

# director 찾기
def find_director(find_dir):
    
    if find_dir != "없음":
        words = []
    
        for i in find_dir:
            i = i.get_text()
            tmp = []
            tmp.append(i)
        
            for w in tmp:
                w = w.strip('\n')
                words.append(w)
                director = words[0].split(',')[0]
        
            return director
    
    else:
        return "없음"
            # 링크 접속
def url_search(movie_name):
    url1 = "https://movie.naver.com/movie/search/result.naver?query={}&section=all&ie=utf8".format(movie_name)
    html1 = requests.get(url1)
    soup1 = BeautifulSoup(html1.text, 'html.parser')
    
    return soup1

In [ ]:
def href_tag(soup1):

    tag_search_list1 = soup1.find("ul", class_ = "search_list_1")
    
    if bool(tag_search_list1) == True:
        tag_a = soup1.select('div#old_content > ul.search_list_1 > li > p.result_thumb > a')
        global href
        for i in tag_a:
            href = i.attrs['href']
    
        return href
    
    else:
        return "없음"

In [ ]:
soup1 = url_search('블랙 위도우')

tag_search_list1 = soup1.find("ul", class_ = "search_list_1")
bool(tag_search_list1)